### ISSUE TITLE
hit modul error

### ISSUE THREAD

**Issue by ghost** [aStonedPenguin/pLogs-2#1]
Lua Error: [ERROR] addons/plogs-2-master/lua/plogs_hooks/hitmodule.lua:4: attempt to index a string value with bad key ('NameID' is not part of the string library) 1. error - [C]:-1 2. __index - lua/includes/extensions/string.lua:310 3. fn - addons/plogs-2-master/lua/plogs_hooks/hitmodule.lua:4 4. Call - addons/ulib/lua/ulib/shared/hook.lua:110 5. func - addons/hitmanmenu/lua/autorun/server/sv_hm_main.lua:84 6. unknown - lua/includes/extensions/net.lua:32

**Comment by aStonePenguin** [comment]
You're going to have to tell the author of the hit addon you're using he needs to pass the player entity to the hook not a string.
