### ISSUE TITLE
IP logs and Player Events are not loading.      + time help

### ISSUE THREAD

**Issue by stubb0** [aStonedPenguin/pLogs-2#2]
No error are being reported and i know that they are being recorded thanks to sql

I am also experiencing a problem with the time being recorded in SQL when i go to the phpmyadmin page with the databases it is showing the time as '1459539921' i would find having the time useful as i am making a web page that loads the logs but i am unable to show the time. The time is also the same on steam api so it might just be something i need to look up.

**Comment by stubb0** [comment]
i have found the time it is in unix

**Comment by aStonePenguin** [comment]
yep not an issue
